CXX = g++
CXXFLAGS = -g -Wall -Wextra -Wshadow -ansi -pedantic

all: project1

run:
	./project-1 "CNS 3060" is going to be FUN

clean:
	rm -rf project-1 project-1.dSYM

project1: project1.cpp
	$(CXX) $(CXXFLAGS) project1.cpp -o project-1